blank_issues_enabled: false
contact_links:
  - name: AwB Discord Server
    url: https://discord.awb-clan.de/
    about: If you need something not covered by the issue templates, you can contact us on our discord.
